# -*- coding: utf-8 -*-
"""1. Two Sum.pyinb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTl5p8ASBPfHFKHCdWfmR25fMfnctuTa
"""

class Solution:
    def twoSum(self, nums, target):

        h = {}
        for i, num in enumerate(nums):
            n = target - num
            if n not in h:
                h[num] = i
            else:
                return [h[n], i]