# -*- coding: utf-8 -*-
"""1. Two Sum

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTl5p8ASBPfHFKHCdWfmR25fMfnctuTa
"""

class Solution:
    def twoSum(self, nums, target):
        for i in range(len(nums)):
            for j in range(i + 1, len(nums)):
                if nums[i] + nums[j] == target:
                    return [i, j]