# -*- coding: utf-8 -*-
"""9. Palindrome Number

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DSK27iicB6wpWG_Glu5DewoZ1ubFHUDJ
"""

class Solution:
    def isPalindrome(self, x: int):
        if x < 0:
            return False

        str_x = str(x)

        if str_x == str_x[::-1]:
            return True
        else:
            return False